### ISSUE TITLE
quench tests fail to run in 11.302

### ISSUE THREAD

**Issue by tposney** [Ethaks/FVTT-Quench#306]
I've been using quench for quite a while and I think it's fabulous.
Sadly when I updated foundry to 11.302 I now get the error
```
foundry.js:66514 Uncaught (in promise) Error: undefined. Directory __snapshots__/quench/quench.midi-qol.tests does not exist or is not accessible in this storage location
[No packages detected]
    at a.<anonymous> (foundry.js:66514:43)
    at a.value (socket.js:532:17)
    at a.value (socket.js:459:22)
    at L.emit (index.mjs:136:20)
    at manager.js:207:18
    ```

I don't use any snapshots and the error has not  occurred in 11.301 or earlier. I don't actually know what's going on so any help in resolving would be much appreciated.

**Comment by Ethaks** [comment]
It looks like 11.302 (might've been an earlier v11 build, but I did not encounter this in those builds I tested previously) changed what `FilePicker` throws. The latest release [v0.9.2](https://github.com/Ethaks/FVTT-Quench/releases/tag/v0.9.2) should fix that.

**Comment by tposney** [comment]
That was fast - many thanks
